# Generated by Django 4.1.5 on 2023-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profilepic', models.ImageField(upload_to='pics')),
                ('intro', models.TextField()),
            ],
        ),
    ]
