# Generated by Django 4.1.5 on 2023-08-09 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Course",
        ),
    ]
