# Generated by Django 4.1.5 on 2023-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0002_rename_product_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=250)),
                ("mobile", models.IntegerField()),
                ("address", models.CharField(max_length=250)),
                ("dob", models.DateField(max_length=250)),
                ("dept", models.CharField(max_length=250)),
                ("course", models.CharField(max_length=250)),
                ("purpose", models.CharField(max_length=250)),
                ("material", models.CharField(max_length=250)),
            ],
        ),
    ]
